### ISSUE TITLE
Product Image URLs broken by /media/media/

### ISSUE THREAD

**Issue by xantek-imc** [Reflektion/reflektion_magento_2#16]
An extra 'media' is being added to the product feed URLs due to:
https://github.com/Reflektion/reflektion_magento_2/commit/e63ef19e0063a5603e165874dfaa6e440eb99870#diff-43cf5294a590700e70cf32ba127563b1

Here the $baseUrlWp is set to the Magento base media URL
https://github.com/Reflektion/reflektion_magento_2/blob/fa1271258622e2fe931d6b9dffc897af57ae165a/Model/Feed/Product.php#L198-L201

Here 'media' is being added to the product image URLs
https://github.com/Reflektion/reflektion_magento_2/blob/fa1271258622e2fe931d6b9dffc897af57ae165a/Model/Feed/Product.php#L239-L256

**Comment by prashantreflektion** [comment]
Thank you Ian.

Fixed - https://github.com/Reflektion/reflektion_magento_2/pull/17
