### ISSUE TITLE
Category Feed - missing SEO rewrite URL

### ISSUE THREAD

**Issue by xantek-imc** [Reflektion/reflektion_magento_2#4]
https://github.com/Reflektion/reflektion_magento_2/blob/d64d9777998de1c632cf552a98cb76b68d4df362/Model/Feed/Category.php#L177

Since 
`->addUrlRewriteToResult()`

You can get Category URL via:
`$catData[$i]['url'] = $category->getRequestPath();`

**Comment by prashantreflektion** [comment]
Thank you Ian
Fixed issue.
